apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-check-service
  template:
    metadata:
      labels:
        app: health-check-service
    spec:
      containers:
      - name: health-check-service
        image: your-docker-registry/health-check-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: health-check-service
spec:
  selector:
    app: health-check-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer

